name: test build

on:
  push:
    branches-ignore: ["stable"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: lint code
        run: ruff check --output-format=github --target-version=py311

      - name: check code formatting
        run: ruff format --diff --target-version=py311

      - name: install uv
        uses: astral-sh/setup-uv@v7

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: install project
        run: uv sync --locked --all-extras --dev

      - name: tun tests
        run: uv run pytest tests

      - name: build package
        run: python -m build

      - name: verify build artifacts
        run: |
          echo "showing build artifacts..."
          ls -la dist/
          echo ""
          echo "package contents:"
          twine check dist/*
